travis:
  secure:
    BINSTAR_TOKEN: lUddIee7Ui5SX1/oWsR8DQosdhufOXyuk9+OGEXT+38sB5o0Bq7efmqLJ9dwzKiA1881geVPsQAhgr/3r05UAEAcf9/y1gWy5/CBAovr2OMH96Q4P4mYMN95W1OkQHSrGqwktsAFzjGBu2OL/ZfkKzmKKZlFB1SEjN3iZvj8rWMr2z4tSy/+cjNsfdrDqbhoGL2KMu/hAFSWZinZi+trcmIe8j/7ZQExrEEfNrdw5cv2tgjk6yRbG4Meju0kiH5gn6B3MC8h5wmhw8S41mqXB8q+mK89+de5xZYQCsnhSVf/xx5BTm+4pRh2C58Svixal+bmsi0WTDFreVjVxEsn1NqHnA1vKXdeZxJg6QyHhbLWmxYLTPPVyHvdqTFXyud2DzIJQHk7gAACw8RQC8IWEX6qlL9BhJ4JcZojrGNIOJ/A8hzCeGQ6sHh4yBqX3Yoq6Eyia4dcsovGmkcrBBBaeP4sjLiSO6IvkT74TrN3LiCZ1Nj9CkjXVextd+7x1/44O6Ryy0j0Z4LNu/uN3s8DAgcBFn4kPANCHxDIVVsTXfBGsPq1myUrAivDBQSn33c3rMRxc+hHUdLFiwSnfbs9BZFHZ0u2q2syWakrUmB869aPP72N5iTSlP9YzNXkW9ZEE5HG5/XVfg1UgtOGMSaBUoVGKH1yx0ZvLe+j0Fl1/Ns=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
